#!/bin/bash

# Clear terminal screen
clear

echo -e "\033[96m"
echo "  /\\  | o  _  ._   /\\  \\  /"
echo " /--\\ | | (_| | | /--\\  \\/ "
echo "           _|              "
echo -e "\033[0m"
echo -e "\033[1mAlignAV — Container Security Simulator\033[0m"
echo "=========================================================="
echo "This zero-cloud local simulation replicates the core security"
echo "features of Azure IoT Edge container environments."
echo ""
echo -e "\033[1;92m🚀 Instructions to Run the Simulation:\033[0m"
echo "----------------------------------------------------------"
echo -e "1. \033[1mStart the Security Hub & Dashboard\033[0m (Cloud Services)"
echo "   Run this command in Terminal Window 1:"
echo -e "   \033[93mpython3 mock_iot_hub.py\033[0m"
echo -e "   Open Dashboard: \033[94mhttp://localhost:8080\033[0m"
echo ""
echo -e "2. \033[1mBootstrap the Edge Gateway Daemon\033[0m (Hardware host)"
echo "   Run this command in Terminal Window 2:"
echo -e "   \033[93mpython3 mock_edge_device.py\033[0m"
echo "   * Performs TPM 2.0 attestation"
echo "   * Fetches deployment manifest and runs signature scans"
echo "   * Ingests telemetry (visible in the stream table)"
echo ""
echo -e "3. \033[1mSimulate Security Threats\033[0m (CLI commands)"
echo "   Run these commands in Terminal Window 3 to trigger breaches:"
echo -e "   - Host Escape: \033[91mpython3 mock_edge_device.py escape\033[0m"
echo -e "   - Port Scan:   \033[91mpython3 mock_edge_device.py portscan\033[0m"
echo -e "   - Re-secure:   \033[92mpython3 mock_edge_device.py restore\033[0m"
echo "=========================================================="
echo "Observe the dashboard update in real-time as alerts trigger!"
echo ""
